# Default config file for polymer dynamics (reduced coordinate case)

# temperature: 1.0 # non-dim temperature set to be 1.0, varying temperature can be given in args
dt: 0.0005 # TODO: get rid of explicit dt in the config file

dim: 3
# args: 2

data:
  repo:
    "MLDS-NUS/Wis_T_Reduced" # data repository
    #repo_val: "MLDS-NUS/Fs_Validation_Reduced" # validation repository
    # splits: ["F23_10_T1"]
    #  splits: ["F23_10_T0_25","F23_10_T0_5","F23_10_T2_25","F23_10_T5","F23_10_T10","F23_10_T1","F1_62_T1","F1_62_T10","F1_62_T5","F1_62_T2_25","F1_62_T0_25","F1_62_T0_5","F3_92_T2_25","F0_38_T0_25","F2_31_T1","F2_78_T1","F3_93_T1","F4_63_T1","F11_60_T1","F16_20_T1","F56_00_T2_25","F5_47_T0_25"]
    # splits: ["F23_10_T0_25","F23_10_T1","F23_10_T2_25","F23_10_T5","F1_62_T1","F1_62_T5","F1_62_T0_5","F3_92_T2_25","F4_63_T1"]
  splits:
    - Wi10_T0
    - Wi10_T1
    - Wi10_T2
    # - Wi07_T0
    # - Wi07_T1
    # - Wi07_T2
    # - Wi1_T1
    # - Wi1_2_T1
    # - Wi1_7_T1
    # - Wi2_T1
    # - Wi5_T1
    # - Wi7_T1
model:
  seed: 0 # random seed
  potential:
    activation: "srequ" # shifted ReQU activation
    alpha: 0.01 # regularization strength
    units: # layer sizes
      - 128
    n_pot: 32
    param_dim: 2
  dissipation:
    activation: "tanh"
    alpha: 0.01
    units:
      - 32
      - 32
  conservation:
    activation: "tanh"
    units:
      - 32
      - 32
  diffusion:
    alpha: 0.01
    units:
      - 32
      - 32
    activation: "srequ"
    param_dim: 2

train:
  num_epochs: 1000 # number of epochs for training the SDE
  batch_size: 64 # each batch will be [batch_size, train_traj_len, dim], so use a small batch size if train_traj_len is large
  train_traj_len: 250 # can shrink the length of the training trajectories for better GPU performance
  checkpoint_every: 100 # number of epochs to check-point the model
  loss: # loss weights
    recon_weight: 1.0e-3
    compare_weight: 100.0
  opt: # optimiser options
    learning_rate: 1.0e-3
  rop: # reduce on plateau options
    patience: 20
    cooldown: 20
    factor: 0.4
    rtol: 1.0e-4
    min_scale: 1.0e-4
    accumulation_size: 2000

hydra:
  run:
    dir: ./outputs/${now:%Y_%m_%d-%H_%M_%S}
  sweep:
    dir: ./outputs/multirun/${now:%Y_%m_%d-%H_%M_%S}
    subdir: ${hydra.job.num}
